#!/usr/bin/env python3
"""Step 8: validate predictions against the source corpora's binary labels.

This is an external weak check, not human gold. It reports neutral predictions
as abstentions and writes a reproducible JSON/Markdown summary under ``reports/``.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from src.config import load_config
from src.data import load_jsonl_dicts
from src.labels import coerce_label
from src.metrics import classification_summary
from src.validation import fallback_abstentions, validate_binary


def _index_by_id(path: Path, label_keys: tuple[str, ...]) -> dict[str, str]:
    rows = load_jsonl_dicts(path)
    index: dict[str, str] = {}
    for row in rows:
        row_id = str(row["id"])
        if row_id in index:
            raise ValueError(f"duplicate id {row_id} in {path}")
        raw_label = next((row[key] for key in label_keys if row.get(key) is not None), None)
        if raw_label is None:
            raise ValueError(f"missing label keys {label_keys} for id {row_id} in {path}")
        index[row_id] = coerce_label(raw_label)
    return index


def _aligned(
    gold_ids: list[str],
    index: dict[str, str],
    model: str,
) -> list[str]:
    missing = [row_id for row_id in gold_ids if row_id not in index]
    if missing:
        preview = ", ".join(missing[:5])
        raise ValueError(f"{model} is missing {len(missing)} gold ids: {preview}")
    return [index[row_id] for row_id in gold_ids]


def _select_student(results_dir: Path, override: str | None) -> Path:
    if override:
        path = Path(override)
        return path if path.is_absolute() else ROOT / path

    candidates = sorted((results_dir / "predictions").glob("*_predictions.jsonl"))
    if len(candidates) == 1:
        return candidates[0]
    if not candidates:
        raise FileNotFoundError(
            f"no student predictions under {results_dir / 'predictions'}; "
            "pass --student-predictions"
        )
    names = ", ".join(path.name for path in candidates)
    raise ValueError(
        f"multiple student prediction files found ({names}); "
        "pass --student-predictions"
    )


def _round_summary(summary: dict) -> dict:
    return {
        "accuracy": round(summary["accuracy"], 4),
        "macro_f1": round(summary["macro_f1"], 4),
        "per_class_f1": {
            label: round(value, 4)
            for label, value in summary["per_class_f1"].items()
        },
        "support": summary["support"],
    }


def _round_validation(summary: dict) -> dict:
    out = dict(summary)
    for key in ("coverage", "covered_accuracy", "accuracy_neutral_as_error", "balanced_recall"):
        out[key] = round(out[key], 4)
    out["recall"] = {key: round(value, 4) for key, value in out["recall"].items()}
    return out


def _pct(value: float) -> str:
    return f"{value * 100:.2f}%"


def _markdown(report: dict) -> str:
    consistency = report["teacher_proposal_consistency"]
    external = report["external_binary_validation"]
    lines = [
        "# Binary External Validation",
        "",
        "Generated by `python3 scripts/8_validate_binary.py`.",
        "",
        "> The source corpora provide only noisy two-class labels. This report is an "
        "external weak check, not a human gold evaluation. `neutral` is treated as "
        "an abstention in coverage and as incorrect in `neutral-as-error accuracy`.",
        "",
        "## Teacher-proposal consistency",
        "",
        "| model | accuracy | macro-F1 | neutral F1 |",
        "|---|---:|---:|---:|",
    ]
    for model, summary in consistency.items():
        lines.append(
            f"| {model} | {summary['accuracy']:.4f} | {summary['macro_f1']:.4f} | "
            f"{summary['neutral_f1']:.4f} |"
        )

    lines += [
        "",
        "## Weak binary check",
        "",
        "| model | coverage | covered accuracy | neutral-as-error accuracy | "
        "negative recall | positive recall |",
        "|---|---:|---:|---:|---:|---:|",
    ]
    for model, summary in external.items():
        lines.append(
            f"| {model} | {_pct(summary['coverage'])} | "
            f"{_pct(summary['covered_accuracy'])} | "
            f"{_pct(summary['accuracy_neutral_as_error'])} | "
            f"{_pct(summary['recall']['negative'])} | "
            f"{_pct(summary['recall']['positive'])} |"
        )

    lines += [
        "",
        "## Pairwise three-class agreement",
        "",
        "| pair | agreement |",
        "|---|---:|",
    ]
    for pair, value in report["pairwise_agreement"].items():
        lines.append(f"| {pair} | {_pct(value)} |")

    lines += [
        "",
        "## Limits",
        "",
        "- The two-class source labels are noisy and cannot validate `neutral`.",
        "- The teacher-proposal table uses the teacher as its own reference, so the "
        "teacher row is 1.0 by construction.",
        "- Human annotation remains required before claiming publication-grade "
        "three-class performance.",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--gold", default="data/splits/gold.jsonl")
    parser.add_argument("--teacher", default="results/gold_teacher_proposals.jsonl")
    parser.add_argument("--baseline", default="results/baseline_predictions.jsonl")
    parser.add_argument("--student-predictions", default=None)
    parser.add_argument("--out-json", default=None)
    parser.add_argument("--out-md", default=None)
    args = parser.parse_args()

    cfg = load_config()
    results_dir = ROOT / cfg.get("paths.results_dir", "results")
    reports_dir = ROOT / cfg.get("paths.reports_dir", "reports")

    def resolve(path: str) -> Path:
        value = Path(path)
        return value if value.is_absolute() else ROOT / value

    gold_path = resolve(args.gold)
    teacher_path = resolve(args.teacher)
    baseline_path = resolve(args.baseline)
    student_path = _select_student(results_dir, args.student_predictions)
    out_json = resolve(args.out_json) if args.out_json else reports_dir / "binary_validation.json"
    out_md = resolve(args.out_md) if args.out_md else reports_dir / "binary_validation.md"

    gold_rows = load_jsonl_dicts(gold_path)
    gold_ids = [str(row["id"]) for row in gold_rows]
    if len(set(gold_ids)) != len(gold_ids):
        raise ValueError(f"duplicate ids in {gold_path}")
    targets = [row.get("source_label") for row in gold_rows]

    teacher = _aligned(gold_ids, _index_by_id(teacher_path, ("teacher_label",)), "teacher")
    baseline = _aligned(gold_ids, _index_by_id(baseline_path, ("label", "prediction")), "baseline")
    student = _aligned(
        gold_ids,
        _index_by_id(student_path, ("label", "prediction")),
        "student",
    )
    student_fallback = fallback_abstentions(student, baseline)
    teacher_fallback = fallback_abstentions(teacher, baseline)

    predictions = {
        "teacher": teacher,
        "student": student,
        "baseline": baseline,
        "student_neutral_fallback_baseline": student_fallback,
        "teacher_neutral_fallback_baseline": teacher_fallback,
    }
    external = {
        model: _round_validation(validate_binary(targets, labels))
        for model, labels in predictions.items()
    }

    consistency = {
        model: _round_summary(classification_summary(teacher, labels))
        for model, labels in predictions.items()
        if model in ("teacher", "student", "baseline")
    }
    agreement = {
        "student_vs_teacher": sum(a == b for a, b in zip(student, teacher)) / len(gold_ids),
        "baseline_vs_teacher": sum(a == b for a, b in zip(baseline, teacher)) / len(gold_ids),
        "student_vs_baseline": sum(a == b for a, b in zip(student, baseline)) / len(gold_ids),
    }
    report = {
        "schema_version": 1,
        "n": len(gold_ids),
        "evaluation_boundary": {
            "teacher_proposals": "not human gold",
            "external_source_labels": "noisy two-class weak check",
            "neutral": "abstention in coverage; error in neutral-as-error accuracy",
        },
        "artifacts": {
            "gold": str(gold_path.relative_to(ROOT)),
            "teacher": str(teacher_path.relative_to(ROOT)),
            "student": str(student_path.relative_to(ROOT)),
            "baseline": str(baseline_path.relative_to(ROOT)),
        },
        "teacher_proposal_consistency": {
            model: {
                "accuracy": round(summary["accuracy"], 4),
                "macro_f1": round(summary["macro_f1"], 4),
                "neutral_f1": round(summary["per_class_f1"]["neutral"], 4),
            }
            for model, summary in consistency.items()
        },
        "external_binary_validation": external,
        "pairwise_agreement": {
            key: round(value, 4) for key, value in agreement.items()
        },
    }

    out_json.parent.mkdir(parents=True, exist_ok=True)
    out_md.parent.mkdir(parents=True, exist_ok=True)
    out_json.write_text(
        json.dumps(report, ensure_ascii=False, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    out_md.write_text(_markdown(report), encoding="utf-8")

    print(
        f"[8_validate_binary] n={len(gold_ids)}  "
        f"student coverage={external['student']['coverage']:.3f}  "
        f"student covered_acc={external['student']['covered_accuracy']:.3f}  "
        f"student neutral-as-error={external['student']['accuracy_neutral_as_error']:.3f}"
    )
    print(f"[8_validate_binary] -> {out_json}")
    print(f"[8_validate_binary] -> {out_md}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
